fix(migrate): use the right node version (without >=)
Kikobeats/nodengine pull request #22
Opened 2016-10-17 15:17 UTC by clementprevot

2016-10-17 15:18 UTC, clementprevot commented
My previous fix for this was bugged because of a mis-interpretation of the node version to a redirect.

2016-10-17 15:20 UTC, Kikobeats commented
@clementprevot I refactor the code. Can you merge master?

2016-10-17 15:22 UTC, clementprevot commented
I saw that, I was merging the conflicts. You are way too fast for me :wink:

2016-10-17 15:37 UTC, Kikobeats commented
haha, but you resolve the conflict using the previous version!

2016-10-17 15:46 UTC, clementprevot commented
Really? Hum that's weird, let me check that

2016-10-17 15:48 UTC, clementprevot commented
@Kikobeats Are you sure? When I look at the changes of the PR, I only see the changes to use the right node version (variable name `currentVersion` in both `index.js` and `switcher.js` files

2016-10-17 15:50 UTC, Kikobeats commented on bin/index.js
> +
can you remove this extra line?

2016-10-17 15:52 UTC, Kikobeats commented
@clementprevot lol you're right, I added comments 👍

2016-10-17 15:54 UTC, clementprevot commented on bin/index.js
> +
Done

2016-10-18 13:27 UTC, Kikobeats commented
Need to resolve the pending reviews before merge this

2016-10-18 13:30 UTC, clementprevot commented
I don't see any pending review

2016-10-18 13:47 UTC, Kikobeats requested changes

2016-10-18 13:47 UTC, Kikobeats commented on bin/index.js
> +  var currentVersion = process.versions.node
If you are tying to switch the version, this version refers the old version.

For sanetize the version, use `semver.sanetize`:

```
semver.clean('  =v1.2.3   ') // '1.2.3'
```

2016-10-18 13:47 UTC, Kikobeats commented on bin/switcher.js
`var semver = require('semver')` here

2016-10-18 13:47 UTC, Kikobeats commented on bin/switcher.js
>    cmd += maxSatisfyVersion
`cmd += semver.clean(maxSatisfyVersion)` here

2016-10-18 13:48 UTC, Kikobeats commented
was (again) my fault, check now 😄

2016-10-18 13:51 UTC, clementprevot commented on bin/index.js
> +  var currentVersion = process.versions.node
No, I precisely want to get the current (so the old) version of node, to be able to tell to NVM to migrate already installed package from this version.

e.g: we are in node 6.7.0, NVM detects a new 6.8.1 version, I want to migrate packages from 6.7.0 so the command line is `nvm install 6.8.1 --resinstall-packages-from=6.7.0`. That's the main goal of the `currentVersion` param given to the `createSwitcher` function

2016-10-18 13:51 UTC, clementprevot commented on bin/switcher.js
See my previous comment, thus, not needed

2016-10-18 13:51 UTC, clementprevot commented on bin/switcher.js
>    cmd += maxSatisfyVersion
See again my first comment

2016-10-18 13:52 UTC, clementprevot commented
I commented on your reviews. I think you misunderstood what I wanted to do :wink:

2016-10-18 17:47 UTC, Kikobeats approved these changes

2016-10-18 17:47 UTC, Kikobeats commented
yay!

2016-10-18 17:47 UTC, merged